name: Lint GitHub Actions
on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
      - "**/action.yml"
      - "**/action.yaml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  actionlint:
    name: actionlint
    permissions:
      contents: read # Required to checkout the repository
      security-events: write # add zizmor security events
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      ACTIONLINT_VERSION: 03d0035246f3e81f36aed592ffb4bebf33a03106 # v1.7.7
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Check workflow files
        run: |
          set -euo pipefail

          bash <(curl "https://raw.githubusercontent.com/rhysd/actionlint/${ACTIONLINT_VERSION}/scripts/download-actionlint.bash")
          ./actionlint -format "$(cat .github/workflows/actionlint-format.txt)" | tee results.sarif
        shell: bash

      - name: Upload to GitHub security events
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@38e701f46e33fb233075bf4238cb1e5d68e429e4 # v3.31.11
        with:
          sarif_file: results.sarif
          category: actionlint

  zizmor:
    name: zizmor
    permissions:
      contents: read # Required to checkout the repository
      security-events: write # add zizmor security events
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Run zizmor ðŸŒˆ
        uses: zizmorcore/zizmor-action@135698455da5c3b3e55f73f4419e481ab68cdd95 # v0.4.1
        with:
          persona: pedantic

  summary:
    if: always()
    needs: [actionlint, zizmor]
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          set -euo pipefail

          cat <<EOF>> "${GITHUB_STEP_SUMMARY}"
          ## Linting Results
          | Tool | Status |
          |------|--------|
          | actionlint | "${NEEDS_ACTIONLINT_RESULT}" |
          | zizmor | "${NEEDS_ZIZMOR_RESULT}" |

          EOF

        env:
          NEEDS_ACTIONLINT_RESULT: ${{ needs.actionlint.result }}
          NEEDS_ZIZMOR_RESULT: ${{ needs.zizmor.result }}
