name: Renovate Validate

on:
  pull_request:
    paths:
      - ".github/workflows/**.ya?ml"
      - "default.json"
      - "extends/**.json"
      - "package-lock.json"
      - "package.json"
      - "renovate.exsample.json"
      - "renovate.json"
      - "yarn.lock"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  validator:
    name: vaildator
    permissions:
      contents: read # Required to checkout the repository
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 22

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: node_modules
          key: node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: Run renovate-config-validator
        run: |
          set -eu

          for file in $(find . -maxdepth 2 -type f -name "*.json" -not -name package.json -not -name package-lock.json | sort); do
            echo -e "Validate ${file}\n"
            set -x
            npx --yes --package renovate -- renovate-config-validator --strict "${file}"
            set +x
          done
